Repository ufs-community/ufs-srweather-app, pull requests merged in 2021-02, with the labels that each got.

#105 Update path to fix files and sample model data on AWS
  docs/UsersGuide/source/InputOutputFiles.rst
Labels: documentation

#114 Feature/add license to release/public-v1
  LICENSE.md
  README.md
Labels: release

#117 Feature/config new platform Final update to Input/Output Files Chapter
  docs/UsersGuide/source/InputOutputFiles.rst
Labels: documentation, release

#116 Feature/doc updates to release/public-v1
  docs/UsersGuide/source/Introduction.rst
  docs/UsersGuide/source/Quickstart.rst
Labels: release
