Repository ufs-community/ufs-srweather-app, pull requests merged in 2022-06, with the labels that each got.

#288 updating hash of UPP to upp_v10.1.0 release
  Externals.cfg
Labels: run_ci

#294 Update Spack Stack Location for NOAA Cloud
  modulefiles/build_noaacloud_intel
Labels: run_ci

#266 Update srw_common and hashes of UFS_UTILS and UPP
  Externals.cfg
  modulefiles/build_cheyenne_gnu
  modulefiles/build_cheyenne_intel
  modulefiles/build_gaea_intel
  modulefiles/build_hera_intel
  modulefiles/build_jet_intel
  modulefiles/build_orion_intel
  modulefiles/srw_common
  modulefiles/wflow_jet
  src/CMakeLists.txt
Labels: Tested on Hera, Tested on Cheyenne, Tested on Jet, run_ci, Tested on Orion

#311 [release/public-v2] Updating WM to ufs-community umbrella
  Externals.cfg
Labels: run_ci

#312 [release/public v2]: Final documentation edits
  README.md
  docs/UsersGuide/source/BuildRunSRW.rst
  docs/UsersGuide/source/Components.rst
  docs/UsersGuide/source/ConfigWorkflow.rst
  docs/UsersGuide/source/InputOutputFiles.rst
  docs/UsersGuide/source/Introduction.rst
  docs/UsersGuide/source/Non-ContainerQS.rst
  docs/UsersGuide/source/Quickstart.rst
Labels: documentation, release, Work in Progress

#306 [develop] Update hash of ufs weather model
  Externals.cfg
Labels: Tested on Hera, Tested on Orion
