Repository ufs-community/ufs-srweather-app, pull requests merged in 2022-10, with the labels that each got.

#391 Temporary fix for Hera netcdf issue.
  modulefiles/build_hera_intel
  modulefiles/srw_common
  ush/load_modules_run_task.sh
Labels: bug, Priority: HIGH

#396 Fixes issue #395 regarding use of `@` character in experiment path
  parm/FV3LAM_wflow.xml
  tests/WE2E/get_expts_status.sh
  tests/WE2E/test_configs/wflow_features/config.deactivate_tasks.yaml
  ush/machine/cheyenne.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/noaacloud.yaml
  ush/machine/odin.yaml
  ush/machine/stampede.yaml
  ush/setup.py
Labels: bug

#378 [develop] Common infrastructure for CIs and manual runs
  .cicd/Jenkinsfile
  .cicd/scripts/srw_build.sh
  .cicd/scripts/srw_test.sh
  test/build.sh
  tests/WE2E/get_expts_status.sh
  tests/WE2E/machine_suites/comprehensive
  tests/WE2E/machine_suites/fundamental
  tests/WE2E/setup_WE2E_tests.sh
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/get_crontab_contents.py
  ush/launch_FV3LAM_wflow.sh
  ush/machine/gaea.yaml
Labels: Priority: HIGH, run_we2e_fundamental_tests

#403 Fix quoting/escaping in Jenkinsfile
  .cicd/Jenkinsfile
Labels: run_we2e_fundamental_tests

#406 Fix setting of SRW_WE2E_COMPREHENSIVE_TESTS var
  .cicd/Jenkinsfile
Labels: run_we2e_fundamental_tests

#405 Port SRW App to WCOSS2
  .gitignore
  devbuild.sh
  docs/UsersGuide/source/ConfigWorkflow.rst
  modulefiles/tasks/hera/get_extrn_ics.local
  modulefiles/tasks/hera/get_extrn_lbcs.local
  modulefiles/tasks/hera/get_obs.local
  modulefiles/tasks/orion/get_extrn_ics.local
  modulefiles/tasks/orion/get_extrn_lbcs.local
  modulefiles/tasks/wcoss2/get_extrn_ics.local
  modulefiles/tasks/wcoss2/get_extrn_lbcs.local
  modulefiles/tasks/wcoss2/get_obs.local
  modulefiles/tasks/wcoss2/make_grid.local
  modulefiles/tasks/wcoss2/make_ics.local
  modulefiles/tasks/wcoss2/make_lbcs.local
  modulefiles/tasks/wcoss2/run_fcst.local
  modulefiles/tasks/wcoss2/run_vx.local
  modulefiles/wflow_wcoss2
  parm/FV3LAM_wflow.xml
  scripts/exregional_run_fcst.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.yaml
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/launch_FV3LAM_wflow.sh
  ush/load_modules_run_task.sh
  ush/machine/gaea.yaml
  ush/machine/wcoss2.yaml
  ush/setup.py
  ush/valid_param_vals.yaml
  versions/run.ver.wcoss2
Labels: enhancement, run_we2e_fundamental_tests

#407 Bug fix for gaea modulefiles.
  modulefiles/build_gaea_intel
  modulefiles/build_jet_intel
  modulefiles/build_noaacloud_intel
  modulefiles/build_orion_intel
  modulefiles/tasks/gaea/miniconda_regional_workflow
  modulefiles/tasks/noaacloud/get_extrn_ics.local
  modulefiles/tasks/noaacloud/get_extrn_lbcs.local
  modulefiles/tasks/noaacloud/make_grid.local
  modulefiles/tasks/noaacloud/make_ics.local
  modulefiles/tasks/noaacloud/make_lbcs.local
  modulefiles/tasks/noaacloud/make_orog.local
  modulefiles/tasks/noaacloud/make_sfc_climo.local
  modulefiles/tasks/noaacloud/run_fcst.local
  modulefiles/tasks/noaacloud/run_post.local
  modulefiles/wflow_gaea
  modulefiles/wflow_noaacloud
Labels: run_we2e_fundamental_tests

#404 Remove ENV_INIT_SCRIPT and avoid dependency on system python
  etc/lmod-setup.csh
  etc/lmod-setup.sh
  tests/WE2E/setup_WE2E_tests.sh
  ush/config_defaults.yaml
  ush/init_env.sh
  ush/launch_FV3LAM_wflow.sh
  ush/load_modules_run_task.sh
  ush/load_modules_wflow.sh
  ush/machine/cheyenne.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/linux.yaml
  ush/machine/macos.yaml
  ush/machine/noaacloud.yaml
  ush/machine/odin.yaml
  ush/machine/orion.yaml
  ush/machine/singularity.yaml
  ush/machine/stampede.yaml
  ush/machine/wcoss2.yaml
Labels: run_we2e_fundamental_tests

#417 [develop] Update Hera modulefiles to allow the SRW to build and run once again.
  modulefiles/build_hera_intel
  modulefiles/build_jet_intel
  modulefiles/build_orion_intel
  modulefiles/srw_common
Labels: run_we2e_fundamental_tests

#420 [develop] URGENT PATCH: Update run_WE2E_tests.sh
  tests/WE2E/run_WE2E_tests.sh
Labels: bug, Priority: HIGH

#424 Restore correct `conda activate` message for Cheyenne
  modulefiles/wflow_cheyenne.lua
Labels: run_we2e_fundamental_tests

#430 Post merge cleanup: remove old script, consolidate test directories
  .cicd/scripts/srw_build.sh
  tests/README.md
  tests/WE2E/setup_WE2E_tests.sh
  tests/build.sh
  update_fork.pl
Labels: run_we2e_fundamental_tests

#421 Move fixed-file mapping variables out of `config_defaults.yaml`.
  parm/fixed_files_mapping.yaml
  scripts/exregional_run_fcst.sh
  tests/WE2E/run_WE2E_tests.sh
  ush/UFS_plot_domains.py
  ush/check_python_version.py
  ush/check_ruc_lsm.py
  ush/config_defaults.yaml
  ush/create_diag_table_file.py
  ush/create_model_configure_file.py
  ush/generate_FV3LAM_wflow.py
  ush/get_crontab_contents.py
  ush/link_fix.py
  ush/machine/odin.yaml
  ush/preamble.sh
  ush/python_utils/__init__.py
  ush/python_utils/check_for_preexist_dir_file.py
  ush/python_utils/check_var_valid_value.py
  ush/python_utils/config_parser.py
  ush/python_utils/count_files.py
  ush/python_utils/create_symlink_to_file.py
  ush/python_utils/filesys_cmds_vrfy.py
  ush/python_utils/get_charvar_from_netcdf.py
  ush/python_utils/get_elem_inds.py
  ush/python_utils/interpol_to_arbit_CRES.py
  ush/python_utils/print_input_args.py
  ush/python_utils/print_msg.py
  ush/python_utils/test_python_utils.py
  ush/retrieve_data.py
  ush/set_FV3nml_ens_stoch_seeds.py
  ush/set_FV3nml_sfc_climo_filenames.py
  ush/set_cycle_dates.py
  ush/set_extrn_mdl_params.py
  ush/set_gridparams_ESGgrid.py
  ush/set_gridparams_GFDLgrid.py
  ush/set_ozone_param.py
  ush/set_predef_grid_params.py
  ush/set_thompson_mp_fix_files.py
  ush/setup.py
  ush/test_retrieve_data.py
Labels: run_we2e_fundamental_tests

#434 [develop] Remove my_load_any from modulefiles/srw_common.lua and use load_any
  modulefiles/build_cheyenne_intel.lua
  modulefiles/srw_common.lua
Labels: run_we2e_fundamental_tests

#440 Structure and components of COMIN directory in NCO mode are modified
  jobs/JREGIONAL_GET_EXTRN_MDL_FILES
  scripts/exregional_make_ics.sh
  scripts/exregional_make_lbcs.sh
  scripts/exregional_run_fcst.sh
  ush/job_preamble.sh
  versions/run.ver.wcoss2
Labels: run_we2e_fundamental_tests

#436 Avoid the effect of external environment on tasks
  modulefiles/tasks/cheyenne/make_sfc_climo.local.lua
  modulefiles/tasks/gaea/make_sfc_climo.local.lua
  modulefiles/tasks/hera/make_sfc_climo.local.lua
  modulefiles/tasks/jet/make_sfc_climo.local.lua
  modulefiles/tasks/wcoss2/make_sfc_climo.local.lua
  parm/FV3LAM_wflow.xml
  ush/load_modules_run_task.sh
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/noaacloud.yaml
  ush/machine/odin.yaml
  ush/machine/orion.yaml
  ush/machine/singularity.yaml
  ush/machine/stampede.yaml
Labels: run_we2e_fundamental_tests

#438 Bug fix on hera/jet run_vx.local modulefile.
  modulefiles/tasks/hera/run_vx.local.lua
  modulefiles/tasks/jet/run_vx.local.lua
  ush/config_defaults.yaml
  ush/test_retrieve_data.py
Labels: bug, Priority: HIGH, run_we2e_fundamental_tests

#425 [develop] Update Build/Run and ConfigWorkflow Chapters
  docs/UsersGuide/source/BuildRunSRW.rst
  docs/UsersGuide/source/BuildSRW.rst
  docs/UsersGuide/source/Components.rst
  docs/UsersGuide/source/ConfigWorkflow.rst
  docs/UsersGuide/source/ContainerQuickstart.rst
  docs/UsersGuide/source/ContributorsGuide.rst
  docs/UsersGuide/source/FAQ.rst
  docs/UsersGuide/source/Glossary.rst
  docs/UsersGuide/source/Graphics.rst
  docs/UsersGuide/source/InputOutputFiles.rst
  docs/UsersGuide/source/Introduction.rst
  docs/UsersGuide/source/LAMGrids.rst
  docs/UsersGuide/source/Quickstart.rst
  docs/UsersGuide/source/RocotoInfo.rst
  docs/UsersGuide/source/RunSRW.rst
  docs/UsersGuide/source/WE2Etests.rst
  docs/UsersGuide/source/_static/SRW_build_process.png
  docs/UsersGuide/source/_static/SRW_overall_workflow_run.png
  docs/UsersGuide/source/_static/SRW_regional_workflow_gen.png
  docs/UsersGuide/source/_static/SRW_wflow_flowchart.png
  docs/UsersGuide/source/conf.py
  docs/UsersGuide/source/index.rst
  docs/UsersGuide/source/tables/Tests.rst
  ush/config_defaults.yaml
Labels: documentation

#441 Set agent in matrix block instead of child stages
  .cicd/Jenkinsfile
Labels: run_we2e_fundamental_tests
