Repository ufs-community/ufs-srweather-app, pull requests merged in 2022-09, with the labels that each got.

#354 [develop] Update hashes of UFS_UTILS, ufs-weather-model, and UPP
  Externals.cfg
  devbuild.sh
  docs/UsersGuide/source/ContributorsGuide.rst
  modulefiles/srw_common
  sorc/CMakeLists.txt
Labels: run_ci

#372 [develop] Fix the inline-post issue when WRITE_DOPOST is 'true'
  scripts/exregional_run_fcst.sh
Labels: bug

#374 Add gitignore to the app
  .gitignore
Labels: enhancement

#333 Enable AWS Parallel Works platform and Add Comprehensive End-To-End Tests
  .cicd/Jenkinsfile
  .cicd/scripts/srw_build.sh
  .cicd/scripts/srw_test.sh
Labels: run_we2e_comprehensive_tests
