Repository ufs-community/ufs-srweather-app, pull requests merged in 2022-05, with the labels that each got.

#247 update hash of regional workflow
  Externals.cfg
  docs/UsersGuide/source/ConfigWorkflow.rst
Labels: high priority

#253 Check-in Jenkinsfile and unified scripts
  .cicd/Jenkinsfile
  .cicd/scripts/srw_build.sh
  .cicd/scripts/srw_test.sh
Labels: run_ci

#257 Fix for miniconda3 load on Hera
  Externals.cfg
  modulefiles/wflow_hera
Labels: bug

#275 Fix artifact creation for branches with / in name
  .cicd/Jenkinsfile
Labels: run_ci

#240 Include documentation for building/running SRW App on Mac
  docs/UsersGuide/source/BuildRunSRW.rst
  docs/UsersGuide/source/Quickstart.rst
  docs/UsersGuide/source/WE2Etests.rst
Labels: Work in Progress

#284 Update unified test script to run e2e tests
  .cicd/Jenkinsfile
  .cicd/scripts/srw_test.sh
Labels: run_ci
