Repository ufs-community/ufs-srweather-app, pull requests merged in 2022-11, with the labels that each got.

#448 [Release-v2.1.0] Updated comprehensive tests to include WoFS tests for E2E testing
  tests/WE2E/machine_suites/comprehensive
Labels: run_we2e_fundamental_tests, run_we2e_comprehensive_tests

#443 Updates to the NCO mode
  .cicd/Jenkinsfile
  devbuild.sh
  devclean.sh
  jobs/JREGIONAL_GET_EXTRN_MDL_FILES
  jobs/JREGIONAL_RUN_FCST
  modulefiles/tasks/orion/run_vx.local.lua
  modulefiles/tasks/wcoss2/get_extrn_ics.local.lua
  modulefiles/tasks/wcoss2/get_extrn_lbcs.local.lua
  modulefiles/tasks/wcoss2/get_obs.local.lua
  modulefiles/tasks/wcoss2/make_grid.local.lua
  modulefiles/tasks/wcoss2/make_ics.local.lua
  modulefiles/tasks/wcoss2/make_lbcs.local.lua
  modulefiles/tasks/wcoss2/make_sfc_climo.local.lua
  modulefiles/tasks/wcoss2/python_regional_workflow.lua
  modulefiles/tasks/wcoss2/run_fcst.local.lua
  modulefiles/tasks/wcoss2/run_vx.local.lua
  parm/FV3LAM_wflow.xml
  scripts/exregional_get_extrn_mdl_files.sh
  scripts/exregional_make_ics.sh
  scripts/exregional_make_lbcs.sh
  scripts/exregional_run_fcst.sh
  scripts/exregional_run_post.sh
  tests/WE2E/machine_suites/fundamental.cheyenne
  tests/WE2E/machine_suites/fundamental.cheyenne.gnu
  tests/WE2E/machine_suites/fundamental.gaea
  tests/WE2E/machine_suites/fundamental.hera.nco
  tests/WE2E/machine_suites/fundamental.jet
  tests/WE2E/machine_suites/fundamental.orion
  tests/WE2E/run_WE2E_tests.sh
  ush/calculate_cost.py
  ush/config.nco.yaml
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/get_crontab_contents.py
  ush/job_preamble.sh
  ush/link_fix.py
  ush/load_modules_run_task.sh
  ush/machine/wcoss2.yaml
  ush/retrieve_data.py
  ush/set_gridparams_GFDLgrid.py
  ush/set_ozone_param.py
  ush/set_predef_grid_params.py
  ush/set_thompson_mp_fix_files.py
  ush/setup.py
  versions/build.ver.wcoss2
  versions/run.ver.wcoss2
Labels: run_we2e_fundamental_tests

#457 Fix time offset issue on ICS with GFS nemsio and netcdf files and add new archive file name on HPSS
  jobs/JREGIONAL_GET_EXTRN_MDL_FILES
  parm/FV3LAM_wflow.xml
  parm/data_locations.yml
  scripts/exregional_get_extrn_mdl_files.sh
  tests/WE2E/machine_suites/fundamental.cheyenne.gnu
  tests/WE2E/test_configs/grids_extrn_mdls_suites_nco/config.nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_timeoffset_suite_GFS_v16.yaml
  ush/machine/wcoss2.yaml
  ush/retrieve_data.py
  ush/test_retrieve_data.py
Labels: run_we2e_fundamental_tests

#453 [Release-v2.1.0] Various updates for release
  modulefiles/tasks/orion/run_vx.local.lua
  tests/WE2E/machine_suites/comprehensive
  tests/WE2E/machine_suites/fundamental
  ush/machine/cheyenne.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/noaacloud.yaml
  ush/machine/odin.yaml
  ush/machine/orion.yaml
  ush/machine/stampede.yaml
Labels: Work in Progress

#459 Minor bug fixes
  scripts/exregional_run_post.sh
  sorc/CMakeLists.txt
  tests/WE2E/setup_WE2E_tests.sh
  ush/python_utils/test_data/sample.nc
  ush/setup.py
Labels: run_we2e_fundamental_tests

#461 [develop] Added return code to srw_build.sh script.
  .cicd/scripts/srw_build.sh
  tests/build.sh
Labels: run_we2e_fundamental_tests

#467 Updates for building and running on MacOS (x86_64 and M1)
  etc/lmod-setup.csh
  etc/lmod-setup.sh
  modulefiles/build_macos_gnu.lua
  modulefiles/wflow_macos.lua
Labels: enhancement

#471 [release/public-v2.1.0] Updates for building and running on MacOS (x86_64 and M1)
  etc/lmod-setup.csh
  etc/lmod-setup.sh
  modulefiles/build_macos_gnu.lua
  modulefiles/wflow_macos.lua
Labels: enhancement, release

#472 [release/public-v2.1.0] Plotting script fix: correct a variable name to a lower-case
  ush/Python/plot_allvars.py
  ush/Python/plot_allvars_diff.py
Labels: bug, release

#468 [develop] Patch to correct a variable name to a lower-case
  ush/Python/plot_allvars.py
  ush/Python/plot_allvars_diff.py
Labels: bug

#478 [release/public-v2.1.0] Modulefile updates for generic linux
  modulefiles/build_linux_gnu.lua
  modulefiles/wflow_linux.lua
Labels: release

#475 [develop] bugfix: set PDYext and cycext in get_extrn_ics/lbcs for time-offset
  scripts/exregional_get_extrn_mdl_files.sh
  ush/machine/wcoss2.yaml
Labels: run_we2e_fundamental_tests

#483 [release/public-v2.1.0] Documentation Updates
  README.md
  docs/UsersGuide/source/BuildSRW.rst
  docs/UsersGuide/source/Components.rst
  docs/UsersGuide/source/ConfigWorkflow.rst
  docs/UsersGuide/source/ContainerQuickstart.rst
  docs/UsersGuide/source/ContributorsGuide.rst
  docs/UsersGuide/source/FAQ.rst
  docs/UsersGuide/source/Glossary.rst
  docs/UsersGuide/source/Graphics.rst
  docs/UsersGuide/source/InputOutputFiles.rst
  docs/UsersGuide/source/Introduction.rst
  docs/UsersGuide/source/LAMGrids.rst
  docs/UsersGuide/source/Quickstart.rst
  docs/UsersGuide/source/RocotoInfo.rst
  docs/UsersGuide/source/RunSRW.rst
  docs/UsersGuide/source/WE2Etests.rst
  docs/UsersGuide/source/_static/SRW_build_process.png
  docs/UsersGuide/source/_static/SRW_overall_workflow_run.png
  docs/UsersGuide/source/_static/SRW_run_process.png
  docs/UsersGuide/source/_static/SRW_wflow_input_path.png
  docs/UsersGuide/source/conf.py
  docs/UsersGuide/source/index.rst
  docs/UsersGuide/source/tables/CCPPUpdates.rst
  docs/UsersGuide/source/tables/Tests.csv
  docs/UsersGuide/source/tables/Tests.rst
  docs/UsersGuide/source/tables/fix_file_list.rst
Labels: release

#488 [release/v2.1.0] Bugfix diff plotting script, silence warnings.
  ush/Python/plot_allvars.py
  ush/Python/plot_allvars_diff.py
Labels: release

#466 [develop] Python-based crontab replacement
  .cicd/scripts/srw_test.sh
  tests/WE2E/run_WE2E_tests.sh
  ush/run_srw_tests.py
Labels: run_we2e_fundamental_tests

#492 [develop] Update ufs-weather-model hash and add WoFS_v0 to suites and tests
  Externals.cfg
  parm/FV3.input.yml
  parm/diag_table.FV3_WoFS_v0
  parm/field_table.FV3_WoFS_v0
  scripts/exregional_make_ics.sh
  scripts/exregional_make_lbcs.sh
  sorc/CMakeLists.txt
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0.yaml
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.yaml
  ush/valid_param_vals.yaml
Labels: run_we2e_fundamental_tests
