Repository ufs-community/ufs-srweather-app, pull requests merged in 2023-03, with the labels that each got.

#618 [develop] Reorganize verification tasks (rename tasks and files; split tasks into two)
  jobs/JREGIONAL_RUN_MET_ENSEMBLESTAT_VX_GRID
  jobs/JREGIONAL_RUN_MET_ENSEMBLESTAT_VX_POINT
  jobs/JREGIONAL_RUN_MET_GRIDSTAT_VX
  jobs/JREGIONAL_RUN_MET_GRIDSTAT_VX_ENSMEAN
  jobs/JREGIONAL_RUN_MET_GRIDSTAT_VX_ENSPROB
  jobs/JREGIONAL_RUN_MET_POINTSTAT_VX
  jobs/JREGIONAL_RUN_MET_POINTSTAT_VX_ENSMEAN
  jobs/JREGIONAL_RUN_MET_POINTSTAT_VX_ENSPROB
  parm/FV3LAM_wflow.xml
  parm/metplus/EnsembleStat_SFC.conf
  parm/metplus/EnsembleStat_UPA.conf
  parm/metplus/GridStat_ensmean_APCP01h.conf
  parm/metplus/GridStat_ensmean_APCP03h.conf
  parm/metplus/GridStat_ensmean_APCP06h.conf
  parm/metplus/GridStat_ensmean_APCP24h.conf
  parm/metplus/GridStat_ensmean_REFC.conf
  parm/metplus/GridStat_ensmean_RETOP.conf
  parm/metplus/GridStat_ensprob_APCP01h.conf
  parm/metplus/GridStat_ensprob_APCP03h.conf
  parm/metplus/GridStat_ensprob_APCP06h.conf
  parm/metplus/GridStat_ensprob_APCP24h.conf
  parm/metplus/GridStat_ensprob_REFC.conf
  parm/metplus/GridStat_ensprob_RETOP.conf
  parm/metplus/PointStat_SFC.conf
  parm/metplus/PointStat_UPA.conf
  parm/metplus/PointStat_ensmean_SFC.conf
  parm/metplus/PointStat_ensmean_UPA.conf
  parm/metplus/PointStat_ensprob_SFC.conf
  parm/metplus/PointStat_ensprob_UPA.conf
  scripts/exregional_run_met_ensemblestat_vx_grid.sh
  scripts/exregional_run_met_ensemblestat_vx_point.sh
  scripts/exregional_run_met_gridstat_vx.sh
  scripts/exregional_run_met_gridstat_vx_ensmean.sh
  scripts/exregional_run_met_gridstat_vx_ensprob.sh
  scripts/exregional_run_met_pointstat_vx.sh
  scripts/exregional_run_met_pointstat_vx_ensmean.sh
  scripts/exregional_run_met_pointstat_vx_ensprob.sh
  ush/config_defaults.yaml
Labels: run_we2e_fundamental_tests

#632 [develop] Enable run_post to work with varying forecast length hours
  devbuild.sh
  jobs/JREGIONAL_RUN_POST
  modulefiles/tasks/wcoss2/nexus_gfs_sfc.local.lua
  modulefiles/tasks/wcoss2/run_post.local.lua
  parm/FV3LAM_wflow.xml
  parm/upp-aqm
  scripts/exregional_aqm_lbcs.sh
  scripts/exregional_bias_correction_o3.sh
  scripts/exregional_bias_correction_pm25.sh
  scripts/exregional_get_extrn_mdl_files.sh
  scripts/exregional_make_lbcs.sh
  scripts/exregional_nexus_emission.sh
  scripts/exregional_nexus_gfs_sfc.sh
  scripts/exregional_nexus_post_split.sh
  scripts/exregional_point_source.sh
  scripts/exregional_post_stat_o3.sh
  scripts/exregional_pre_post_stat.sh
  scripts/exregional_run_fcst.sh
  scripts/exregional_run_post.sh
  ush/config.aqm.community.yaml
  ush/config.aqm.nco.realtime.yaml
  ush/generate_FV3LAM_wflow.py
  ush/load_modules_run_task.sh
  ush/setup.py
  versions/run.ver.wcoss2
Labels: run_we2e_fundamental_tests

#627 [develop]: Update for Gaea software stack location and Lmod initialization script
  etc/lmod-setup.sh
  modulefiles/build_gaea_intel.lua
Labels: run_we2e_fundamental_tests

#650 [develop] Fixed issue #649 and tested on cheyenne.
  scripts/exregional_aqm_lbcs.sh
  ush/config_defaults.yaml
  ush/machine/cheyenne.yaml
  ush/machine/hera.yaml
  ush/machine/orion.yaml
  ush/machine/wcoss2.yaml
Labels: run_we2e_fundamental_tests

#670 [develop] Potential bugfix for `run_envir=nco` issue
  ush/config_defaults.yaml
Labels: bug, Priority: HIGH

#659 [develop] Split calling of METplus's PcpCombine tool into separate task (from GridStat and EnsembleStat tasks)
  jobs/JREGIONAL_RUN_MET_PCPCOMBINE
  parm/FV3LAM_wflow.xml
  parm/metplus/EnsembleStat_APCP03h.conf
  parm/metplus/EnsembleStat_APCP06h.conf
  parm/metplus/EnsembleStat_APCP24h.conf
  parm/metplus/GridStat_APCP01h.conf
  parm/metplus/GridStat_APCP03h.conf
  parm/metplus/GridStat_APCP06h.conf
  parm/metplus/GridStat_APCP24h.conf
  parm/metplus/GridStat_REFC.conf
  parm/metplus/GridStat_RETOP.conf
  parm/metplus/GridStat_ensmean_APCP03h.conf
  parm/metplus/GridStat_ensmean_APCP06h.conf
  parm/metplus/GridStat_ensmean_APCP24h.conf
  parm/metplus/GridStat_ensprob_APCP03h.conf
  parm/metplus/GridStat_ensprob_APCP06h.conf
  parm/metplus/GridStat_ensprob_APCP24h.conf
  parm/metplus/PcpCombine_fcst.conf
  parm/metplus/PcpCombine_obs.conf
  parm/metplus/PointStat_SFC.conf
  parm/metplus/PointStat_UPA.conf
  parm/metplus/common.conf
  scripts/exregional_run_met_ensemblestat_vx_grid.sh
  scripts/exregional_run_met_ensemblestat_vx_point.sh
  scripts/exregional_run_met_gridstat_vx.sh
  scripts/exregional_run_met_pcpcombine.sh
  tests/WE2E/test_configs/verification/config.MET_ensemble_verification.yaml
  tests/WE2E/test_configs/verification/config.MET_verification.yaml
  tests/WE2E/test_configs/verification/config.MET_verification_only_vx.yaml
  ush/bash_utils/eval_METplus_timestr_tmpl.sh
  ush/bash_utils/process_args.sh
  ush/config_defaults.yaml
  ush/constants.yaml
  ush/set_vx_fhr_list.sh
  ush/set_vx_params.sh
  ush/source_util_funcs.sh
Labels: run_we2e_fundamental_tests

#679 [develop] Bug fix ensemble_verification in run_envir=nco mode.
  parm/FV3LAM_wflow.xml
Labels: bug, Priority: medium

#664 [develop] Change settings for AQM to meet NCO requirement and improve near-real-time runs
  Externals.cfg
  parm/FV3.input.yml
  parm/aqm.rc
  parm/diag_table_aqm.FV3_GFS_v16
  parm/nems.configure
  scripts/exregional_bias_correction_o3.sh
  scripts/exregional_bias_correction_pm25.sh
  scripts/exregional_pre_post_stat.sh
  ush/config.aqm.nco.realtime.yaml
  ush/machine/wcoss2.yaml
Labels: run_we2e_fundamental_tests

#631 [develop] Add RRFS product generation job to the SRW app
  docs/UsersGuide/source/ConfigWorkflow.rst
  jobs/JREGIONAL_RUN_PRDGEN
  modulefiles/tasks/wcoss2/run_prdgen.local.lua
  parm/FV3LAM_wflow.xml
  scripts/exregional_run_prdgen.sh
  scripts/exregional_run_prdgen_subpiece.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.yaml
  ush/config.community.yaml
  ush/config.nco.yaml
  ush/config_defaults.yaml
  ush/machine/cheyenne.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/linux.yaml
  ush/machine/macos.yaml
  ush/machine/noaacloud.yaml
  ush/machine/odin.yaml
  ush/machine/orion.yaml
  ush/machine/singularity.yaml
  ush/machine/stampede.yaml
  ush/machine/wcoss2.yaml
  ush/valid_param_vals.yaml
Labels: enhancement, help wanted, run_we2e_fundamental_tests

#663 [develop] Update hash of ufs weather model and input.nml/diag_table files
  Externals.cfg
  parm/FV3.input.yml
  parm/diag_table.FV3_GFS_2017_gfdlmp
  parm/diag_table.FV3_GFS_2017_gfdlmp_regional
  parm/diag_table.FV3_GFS_v15_thompson_mynn_lam3km
  parm/diag_table.FV3_GFS_v15p2
  parm/diag_table.FV3_GFS_v16
  parm/diag_table.FV3_GFS_v17_p8
  parm/diag_table.FV3_HRRR
  parm/diag_table.FV3_RRFS_v0
  parm/diag_table.FV3_RRFS_v1beta
  parm/diag_table.FV3_WoFS_v0
  parm/diag_table_aqm.FV3_GFS_v15p2
  parm/diag_table_aqm.FV3_GFS_v16
  parm/diag_table_aqm.FV3_GFS_v17_p8
  parm/input.nml.FV3
  ush/config_defaults.yaml
Labels: run_we2e_fundamental_tests

#685 [develop] Updated cheyenne configs to use new CMAQ shared conda env for tier-1 platforms.
  modulefiles/tasks/cheyenne/aqm_ics.local.lua
  modulefiles/tasks/cheyenne/aqm_lbcs.local.lua
  modulefiles/tasks/cheyenne/fire_emission.local.lua
  modulefiles/tasks/cheyenne/miniconda_regional_workflow_cmaq.lua
  modulefiles/tasks/cheyenne/nexus_emission.local.lua
  modulefiles/tasks/cheyenne/nexus_gfs_sfc.local.lua
  modulefiles/tasks/cheyenne/nexus_post_split.local.lua
  modulefiles/tasks/cheyenne/point_source.local.lua
  modulefiles/tasks/cheyenne/pre_post_stat.local.lua
Labels: run_we2e_fundamental_tests

#674 [develop] Change file paths to EPIC data locations and add fix_gsi var
  docs/UsersGuide/source/ContainerQuickstart.rst
  docs/UsersGuide/source/RunSRW.rst
  ush/machine/cheyenne.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
  ush/machine/noaacloud.yaml
  ush/machine/orion.yaml
Labels: enhancement, Work in Progress, run_we2e_fundamental_tests

#694 [develop] Fix forecast failures for GFS_v16 at 3km
  parm/FV3.input.yml
Labels: bug, run_we2e_fundamental_tests

#699 [develop] Update ufs-weather-model and UPP hash to correct post control file issue
  .cicd/Jenkinsfile
  Externals.cfg
  ush/config_defaults.yaml
Labels: run_we2e_fundamental_tests
