Repository ufs-community/ufs-srweather-app, pull requests merged in 2023-10, with the labels that each got.

#913 [develop] Replace hpc-stack with spack-stack
  modulefiles/build_gaea_intel.lua
  modulefiles/build_hera_gnu.lua
  modulefiles/build_hera_intel.lua
  modulefiles/build_hercules_intel.lua
  modulefiles/build_jet_intel.lua
  modulefiles/build_noaacloud_intel.lua
  modulefiles/build_orion_intel.lua
  modulefiles/srw_common.lua
  modulefiles/srw_common_spack.lua
  modulefiles/tasks/cheyenne/run_vx.local.lua
  modulefiles/tasks/derecho/run_vx.local.lua
  modulefiles/tasks/gaea/run_vx.local.lua
  modulefiles/tasks/hera/run_vx.local.lua
  modulefiles/tasks/hercules/run_vx.local.lua
  modulefiles/tasks/jet/run_vx.local.lua
  modulefiles/tasks/noaacloud/python_srw.lua
  modulefiles/tasks/noaacloud/run_vx.local.lua
  modulefiles/tasks/orion/run_vx.local.lua
  modulefiles/wflow_gaea.lua
  parm/wflow/verify_pre.yaml
  ush/machine/gaea.yaml
  ush/machine/orion.yaml
Labels: run_we2e_coverage_tests

#921 [develop] Update Jenkinsfile to allow automated tests to run simultaneously on Orion/Hercules and Gaea/Gaea C5
  .cicd/Jenkinsfile
  .cicd/scripts/qsub_srw_ftest.sh
  .cicd/scripts/sbatch_srw_ftest.sh
  .cicd/scripts/srw_build.sh
  .cicd/scripts/srw_ftest.sh
  .cicd/scripts/srw_metric_example.sh
  .cicd/scripts/srw_test.sh
  .cicd/scripts/srw_unittest.sh
  .cicd/scripts/wrapper_srw_ftest.sh
  tests/WE2E/test_configs/wflow_features/config.get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS.yaml
Labels: enhancement, run_we2e_coverage_tests

#931 [release/public-v2.2.0] Update Jenkinsfile and Jenkins test scripts to allow the simultaneous run of all tests on all machines
  .cicd/Jenkinsfile
  .cicd/scripts/qsub_srw_ftest.sh
  .cicd/scripts/sbatch_srw_ftest.sh
  .cicd/scripts/srw_build.sh
  .cicd/scripts/srw_ftest.sh
  .cicd/scripts/srw_metric_example.sh
  .cicd/scripts/srw_test.sh
  .cicd/scripts/srw_unittest.sh
  .cicd/scripts/wrapper_srw_ftest.sh
  tests/WE2E/test_configs/wflow_features/config.get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS.yaml
Labels: enhancement, release

#934 [develop] Fix crontab bug for Cheyenne and Derecho, update PR template for new platforms
  .github/PULL_REQUEST_TEMPLATE
  ush/get_crontab_contents.py
Labels: run_we2e_coverage_tests

#939 [release/public-v2.2.0] Fix crontab bug for Cheyenne and Derecho, update PR template for new platforms
  .github/PULL_REQUEST_TEMPLATE
  ush/get_crontab_contents.py
Labels: release

#936 [release/public-v2.2.0] Reactivate comprehensive tests and fix Hera GNU pipeline issues
  .cicd/Jenkinsfile
  .cicd/scripts/wrapper_srw_ftest.sh
Labels: bug, enhancement, release, run_we2e_coverage_tests

#935 [develop] Add Sonarqube stage to the Jenkinsfile for PLATFORM-926
  .cicd/Jenkinsfile
  .cicd/scripts/wrapper_srw_ftest.sh
Labels: enhancement, run_we2e_coverage_tests

#941 [release/public-v2.2.0] spack-stack 1.4.1 integration for Gaea C5 platform
  modulefiles/build_gaea-c5_intel.lua
  modulefiles/tasks/gaea-c5/python_srw.lua
  modulefiles/tasks/gaea-c5/run_vx.local.lua
  modulefiles/wflow_gaea-c5.lua
Labels: enhancement, release, run_we2e_coverage_tests

#937 [Release/public-v2.2.0] Update data paths to v2p2
  modulefiles/build_orion_intel.lua
  parm/wflow/verify_pre.yaml
  tests/WE2E/machine_suites/comprehensive.gaea-c5
  tests/WE2E/machine_suites/comprehensive.noaacloud
  ush/machine/cheyenne.yaml
  ush/machine/derecho.yaml
  ush/machine/gaea-c5.yaml
  ush/machine/gaea.yaml
  ush/machine/hera.yaml
  ush/machine/hercules.yaml
  ush/machine/jet.yaml
  ush/machine/noaacloud.yaml
  ush/machine/orion.yaml
  ush/valid_param_vals.yaml
Labels: release, run_we2e_coverage_tests

#944 [develop] Add comprehensive.gaea-c5 test suite.
  modulefiles/build_orion_intel.lua
  parm/wflow/verify_pre.yaml
  tests/WE2E/machine_suites/comprehensive.gaea-c5
  tests/WE2E/machine_suites/comprehensive.noaacloud
  ush/valid_param_vals.yaml
Labels: run_we2e_coverage_tests

#950 [release/public-v2.2.0]: Documentation Updates
  README.md
  docs/UsersGuide/source/BackgroundInfo/CCPPUpdates.rst
  docs/UsersGuide/source/BackgroundInfo/Components.rst
  docs/UsersGuide/source/BackgroundInfo/Introduction.rst
  docs/UsersGuide/source/BackgroundInfo/TechnicalOverview.rst
  docs/UsersGuide/source/BuildingRunningTesting/AQM.rst
  docs/UsersGuide/source/BuildingRunningTesting/BuildSRW.rst
  docs/UsersGuide/source/BuildingRunningTesting/ContainerQuickstart.rst
  docs/UsersGuide/source/BuildingRunningTesting/Quickstart.rst
  docs/UsersGuide/source/BuildingRunningTesting/RunSRW.rst
  docs/UsersGuide/source/BuildingRunningTesting/Tutorial.rst
  docs/UsersGuide/source/BuildingRunningTesting/VXCases.rst
  docs/UsersGuide/source/BuildingRunningTesting/WE2Etests.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/InputOutputFiles.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/LAMGrids.rst
  docs/UsersGuide/source/Reference/FAQ.rst
  docs/UsersGuide/source/Reference/Glossary.rst
  docs/UsersGuide/source/conf.py
  docs/UsersGuide/source/index.rst
  docs/UsersGuide/source/tables/CCPPUpdates.rst
  docs/UsersGuide/source/tables/Tests.csv
  docs/UsersGuide/source/tables/fix_file_list.rst
Labels: documentation, release
