Repository ufs-community/ufs-srweather-app, pull requests merged in 2024-02, with the labels that each got.

#1012 [develop] Add -n 1 to allow the use of the service partition
  parm/wflow/aqm_prep.yaml
  parm/wflow/verify_pre.yaml
  ush/machine/hera.yaml
  ush/machine/jet.yaml
Labels: run_we2e_coverage_tests

#1014 [develop]: Quarterly Documentation Update (PI11)
  docs/UsersGuide/Makefile
  docs/UsersGuide/source/BackgroundInfo/Components.rst
  docs/UsersGuide/source/BackgroundInfo/Introduction.rst
  docs/UsersGuide/source/BackgroundInfo/TechnicalOverview.rst
  docs/UsersGuide/source/BuildingRunningTesting/AQM.rst
  docs/UsersGuide/source/BuildingRunningTesting/BuildSRW.rst
  docs/UsersGuide/source/BuildingRunningTesting/ContainerQuickstart.rst
  docs/UsersGuide/source/BuildingRunningTesting/Quickstart.rst
  docs/UsersGuide/source/BuildingRunningTesting/RunSRW.rst
  docs/UsersGuide/source/BuildingRunningTesting/Tutorial.rst
  docs/UsersGuide/source/BuildingRunningTesting/VXCases.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/InputOutputFiles.rst
  docs/UsersGuide/source/CustomizingTheWorkflow/LAMGrids.rst
  docs/UsersGuide/source/Reference/FAQ.rst
  docs/UsersGuide/source/SSHIntro.rst
  docs/UsersGuide/source/conf.py
Labels: documentation

#1047 [develop] Update for Gaea-c5
  .cicd/Jenkinsfile
  .cicd/scripts/srw_ftest.sh
  .cicd/scripts/wrapper_srw_ftest.sh
  devbuild.sh
  doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
  etc/lmod-setup.csh
  etc/lmod-setup.sh
  modulefiles/build_gaea_intel.lua
  modulefiles/tasks/gaea-c5/plot_allvars.local.lua
  modulefiles/tasks/gaea-c5/python_srw.lua
  modulefiles/tasks/gaea/plot_allvars.local.lua
  modulefiles/tasks/gaea/python_srw.lua
  modulefiles/tasks/gaea/run_vx.local.lua
  modulefiles/wflow_gaea.lua
  tests/WE2E/machine_suites/comprehensive.gaea
  tests/WE2E/machine_suites/coverage.gaea
  tests/WE2E/setup_WE2E_tests.sh
  tests/build.sh
  ush/load_modules_wflow.sh
  ush/machine/gaea-c5.yaml
  ush/machine/gaea.yaml
  ush/valid_param_vals.yaml
  ush/wrappers/job_cards/sbatch/get_ics.sbatch
  ush/wrappers/job_cards/sbatch/get_lbcs.sbatch
  ush/wrappers/job_cards/sbatch/make_grid.sbatch
  ush/wrappers/job_cards/sbatch/make_ics.sbatch
  ush/wrappers/job_cards/sbatch/make_lbcs.sbatch
  ush/wrappers/job_cards/sbatch/make_orog.sbatch
  ush/wrappers/job_cards/sbatch/make_sfc_climo.sbatch
  ush/wrappers/job_cards/sbatch/run_fcst.sbatch
  ush/wrappers/job_cards/sbatch/run_post.sbatch
Labels: bug, enhancement, run_we2e_coverage_tests, run_we2e_jenkins_coverage_tests
