Repository ufs-community/ufs-srweather-app, pull requests merged in 2025-03, with the labels that each got.

#1213 [develop] Fix cycle being treated as octal integer
  scripts/exregional_get_extrn_mdl_files.sh
Labels: run_we2e_coverage_tests

#1224 [develop] Bug fixes for verification tasks
  parm/data_locations.yml
  parm/wflow/verify_pre.yaml
  ush/config_defaults.yaml
  ush/get_obs.py
  ush/retrieve_data.py
  ush/set_leadhrs.py
Labels: run_we2e_coverage_tests

#1235 [release/public-v3.0.0] Bug fixes for verification tasks
  parm/data_locations.yml
  parm/wflow/verify_pre.yaml
  ush/config_defaults.yaml
  ush/get_obs.py
  ush/retrieve_data.py
  ush/set_leadhrs.py
Labels: bug, release

#1231 [develop] Better field/diag_table handling, enable FV3_HRRR_gf suite for non-smoke/dust cases, update test suites
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  parm/FV3.input.yml
  parm/diag_table.FV3_GFS_v15_thompson_mynn_lam3km
  parm/diag_table.FV3_GFS_v15p2
  parm/diag_table.FV3_GFS_v16
  parm/diag_table.FV3_GFS_v17_p8
  parm/diag_table.FV3_HRRR
  parm/diag_table.FV3_HRRR_gf
  parm/diag_table.FV3_RAP
  parm/diag_table.FV3_RRFS_v1beta
  parm/diag_table.FV3_WoFS_v0
  parm/diag_table.RRFS_sas
  parm/field_table.FV3_HRRR_gf
  tests/README.md
  tests/WE2E/machine_suites/comprehensive.derecho
  tests/WE2E/machine_suites/comprehensive.gaeac5
  tests/WE2E/machine_suites/comprehensive.hera.gnu
  tests/WE2E/machine_suites/comprehensive.hera.intel
  tests/WE2E/machine_suites/comprehensive.noaacloud
  tests/WE2E/machine_suites/comprehensive.orion
  tests/WE2E/machine_suites/coverage.derecho
  tests/WE2E/machine_suites/coverage.gaeac5
  tests/WE2E/machine_suites/coverage.gaeac6
  tests/WE2E/machine_suites/coverage.hera.intel.nco
  tests/WE2E/machine_suites/coverage.hercules
  tests/WE2E/machine_suites/coverage.orion
  tests/WE2E/machine_suites/fundamental
  tests/WE2E/test_configs/custom_grids/config.custom_ESGgrid_Central_Asia_3km.yaml
  tests/WE2E/test_configs/fire/config.UFS_FIRE_multifire_two-way-coupled.yaml
  tests/WE2E/test_configs/fire/config.UFS_FIRE_one-way-coupled.yaml
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.yaml
  tests/WE2E/test_configs/smoke_dust/config.smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf.yaml
  tests/test_python/test_create_diag_table_file.py
  tests/test_python/test_generate_FV3LAM_wflow.py
  ush/config.smoke_dust.yaml
  ush/create_diag_table_file.py
  ush/generate_FV3LAM_wflow.py
  ush/setup.py
Labels: run_we2e_coverage_tests

#1237 [release/public-v3.0.0] Better field/diag_table handling, enable FV3_HRRR_gf suite for non-smoke/dust cases, update test suites
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  parm/FV3.input.yml
  parm/diag_table.FV3_GFS_v15_thompson_mynn_lam3km
  parm/diag_table.FV3_GFS_v15p2
  parm/diag_table.FV3_GFS_v16
  parm/diag_table.FV3_GFS_v17_p8
  parm/diag_table.FV3_HRRR
  parm/diag_table.FV3_HRRR_gf
  parm/diag_table.FV3_RAP
  parm/diag_table.FV3_RRFS_v1beta
  parm/diag_table.FV3_WoFS_v0
  parm/diag_table.RRFS_sas
  parm/field_table.FV3_HRRR_gf
  tests/README.md
  tests/WE2E/machine_suites/comprehensive.derecho
  tests/WE2E/machine_suites/comprehensive.gaeac5
  tests/WE2E/machine_suites/comprehensive.hera.gnu
  tests/WE2E/machine_suites/comprehensive.hera.intel
  tests/WE2E/machine_suites/comprehensive.noaacloud
  tests/WE2E/machine_suites/comprehensive.orion
  tests/WE2E/machine_suites/coverage.derecho
  tests/WE2E/machine_suites/coverage.gaeac5
  tests/WE2E/machine_suites/coverage.gaeac6
  tests/WE2E/machine_suites/coverage.hera.intel.nco
  tests/WE2E/machine_suites/coverage.hercules
  tests/WE2E/machine_suites/coverage.orion
  tests/WE2E/machine_suites/fundamental
  tests/WE2E/test_configs/custom_grids/config.custom_ESGgrid_Central_Asia_3km.yaml
  tests/WE2E/test_configs/fire/config.UFS_FIRE_multifire_two-way-coupled.yaml
  tests/WE2E/test_configs/fire/config.UFS_FIRE_one-way-coupled.yaml
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.yaml
  tests/WE2E/test_configs/smoke_dust/config.smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf.yaml
  tests/test_python/test_create_diag_table_file.py
  tests/test_python/test_generate_FV3LAM_wflow.py
  ush/config.smoke_dust.yaml
  ush/create_diag_table_file.py
  ush/generate_FV3LAM_wflow.py
  ush/setup.py
Labels: bug, release

#1198 [develop] Adding METplus tutorial to Halloween Storm
  doc/UsersGuide/BuildingRunningTesting/Tutorial.rst
Labels: documentation

#1221 [develop] feat: update SRW-SD docs
  .github/scripts/check_tech_doc.sh
  .github/workflows/doc_tests.yaml
  .readthedocs.yaml
  doc/UsersGuide/BuildingRunningTesting/SRW-SD.rst
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  doc/conf.py
  doc/requirements.txt
  doc/tables/SRW-SD_output-variables.csv
Labels: documentation

#1236 [release/public-v3.0.0] Update paths to release data
  .cicd/Jenkinsfile
  ush/machine/derecho.yaml
  ush/machine/gaeac5.yaml
  ush/machine/gaeac6.yaml
  ush/machine/hera.yaml
  ush/machine/hercules.yaml
  ush/machine/noaacloud.yaml
  ush/machine/orion.yaml
Labels: release, run_we2e_coverage_tests

#1202 [develop] Removed all GFDLgrid configuration parameters, predefined grids, and WE2E tests
  doc/TechDocs/ush/modules.rst
  doc/TechDocs/ush/set_gridparams_GFDLgrid.rst
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  scripts/exregional_make_grid.sh
  scripts/exregional_make_ics.sh
  scripts/exregional_make_lbcs.sh
  scripts/exregional_make_orog.sh
  tests/WE2E/machine_suites/comprehensive.derecho
  tests/WE2E/machine_suites/comprehensive.gaeac5
  tests/WE2E/machine_suites/comprehensive.hera.gnu
  tests/WE2E/machine_suites/comprehensive.hera.intel
  tests/WE2E/machine_suites/comprehensive.noaacloud
  tests/WE2E/machine_suites/comprehensive.orion
  tests/WE2E/machine_suites/coverage.hercules
  tests/WE2E/test_configs/custom_grids/config.custom_GFDLgrid.yaml
  tests/WE2E/test_configs/custom_grids/config.custom_GFDLgrid__GFDLgrid_USE_NUM_CELLS_IN_FILENAMES_eq_FALSE.yaml
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16.yaml
  tests/test_python/test_set_gridparams_GFDLgrid.py
  ush/calculate_cost.py
  ush/config_defaults.yaml
  ush/predef_grid_params.yaml
  ush/set_gridparams_GFDLgrid.py
  ush/setup.py
  ush/valid_param_vals.yaml
Labels: run_we2e_coverage_tests

#1234 [release/public-v3.0.0] Updating documentation ahead of v3.0.0 release
  doc/UsersGuide/BuildingRunningTesting/BuildSRW.rst
  doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
  doc/UsersGuide/BuildingRunningTesting/Quickstart.rst
  doc/UsersGuide/BuildingRunningTesting/RunSRW.rst
  doc/UsersGuide/Reference/Glossary.rst
Labels: documentation, release

#1244 [develop] Fix for Issue 1243
  tests/WE2E/test_configs/custom_grids/config.custom_ESGgrid_Great_Lakes_snow_8km.yaml
  tests/WE2E/test_configs/verification/config.MET_verification_smoke_only_vx.yaml
  ush/setup.py
Labels: run_we2e_coverage_tests

#1249 [release/public-v3.0.0] fix: misc smoke/dust updates following stakeholder feedback
  parm/FV3.input.yml
  tests/test_python/test_smoke_dust/conftest.py
  tests/test_python/test_smoke_dust/test_core/test_preprocessor.py
  tests/test_python/test_smoke_dust/test_core/test_regrid.py
  tests/test_python/test_smoke_dust/test_generate_emissions.py
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/smoke_dust/core/context.py
  ush/smoke_dust/core/regrid/common.py
  ush/smoke_dust/core/regrid/processor.py
  ush/smoke_dust/core/variable.py
Labels: bug, documentation, enhancement, release, run_we2e_coverage_tests

#1250 [develop] feat: doc updates around ebb_dcycle and dust_option
  doc/UsersGuide/BuildingRunningTesting/SRW-SD.rst
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
Labels: documentation

#1253 [release/public-v3.0.0] set OMP_NUM_THREADS_RUN_FCST: 1 for noaacloud platforms
  ush/machine/noaacloud.yaml
Labels: release

#1240 [release/public-v3.0.0] Updating Customizing the Workflow chapter
  doc/UsersGuide/BuildingRunningTesting/VXCases.rst
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  doc/UsersGuide/CustomizingTheWorkflow/InputOutputFiles.rst
  doc/UsersGuide/CustomizingTheWorkflow/LAMGrids.rst
Labels: documentation, release

#1252 [release/public-v3.0.0]: Update Background Information Chapter
  doc/UsersGuide/BackgroundInfo/CCPPUpdates.rst
  doc/UsersGuide/BackgroundInfo/Components.rst
  doc/UsersGuide/BackgroundInfo/Introduction.rst
  doc/UsersGuide/BackgroundInfo/TechnicalOverview.rst
  doc/UsersGuide/BuildingRunningTesting/AQM.rst
  doc/UsersGuide/BuildingRunningTesting/BuildSRW.rst
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  doc/UsersGuide/BuildingRunningTesting/Quickstart.rst
  doc/UsersGuide/BuildingRunningTesting/RunSRW.rst
  doc/UsersGuide/BuildingRunningTesting/Tutorial.rst
  doc/UsersGuide/BuildingRunningTesting/VXCases.rst
  doc/UsersGuide/BuildingRunningTesting/WE2Etests.rst
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial1.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial2.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial3.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial4.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial5.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial6.inc
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  doc/UsersGuide/CustomizingTheWorkflow/InputOutputFiles.rst
  doc/UsersGuide/Reference/Glossary.rst
  doc/conf.py
  doc/doc-snippets/clone.rst
  doc/doc-snippets/devbuild.rst
  doc/doc-snippets/expt-conf-intro.rst
  doc/doc-snippets/externals.rst
  doc/references.bib
  doc/requirements.txt
Labels: documentation, release

#1248 [release/public-v3.0.0] Introduce two improvements in setup.py to fix problems with workflow generation
  modulefiles/build_noaacloud_intel.lua
  tests/WE2E/test_configs/custom_grids/config.custom_ESGgrid_Great_Lakes_snow_8km.yaml
  tests/WE2E/test_configs/verification/config.MET_verification_smoke_only_vx.yaml
  ush/setup.py
Labels: bug, release, run_we2e_coverage_tests
