Repository ufs-community/ufs-srweather-app, pull requests merged in 2025-05, with the labels that each got.

#1287 [develop] feat: add UFS-Fire to integration test task
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  jobs/JREGIONAL_INTEGRATION_TEST
  scripts/exregional_integration_test.py
  tests/WE2E/test_configs/fire/config.UFS_FIRE_multifire_two-way-coupled.yaml
  tests/WE2E/test_configs/fire/config.UFS_FIRE_one-way-coupled.yaml
  ush/config_defaults.yaml
Labels: enhancement, Priority: medium

#1290 [develop] fix: pin click to avoid typer failures
  sd_environment.yml
Labels: bug

#1288 [develop] Remove the <exclusive> flags from aqm_prep.yaml and plot.yaml
  .cicd/Jenkinsfile
  .cicd/scripts/srw_metric.sh
  modulefiles/wflow_derecho.lua
  modulefiles/wflow_gaeac6.lua
  parm/wflow/aqm_prep.yaml
  parm/wflow/plot.yaml
  ush/config_defaults.yaml
Labels: bug, run_we2e_coverage_tests

#1297 [Develop] Quick link updates to ensure PRs build correctly
  doc/UsersGuide/Reference/Glossary.rst
  doc/conf.py
Labels: documentation
