Repository ufs-community/ufs-srweather-app, pull requests merged in 2025-04, with the labels that each got.

#1261 Hotfix for Gaea-C6
  modulefiles/build_gaeac6_intel.lua
Labels: bug

#1257 [release/public-v3.0.0] Update to data locations to point to release 3.0 directory
  doc/UsersGuide/BuildingRunningTesting/AQM.rst
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial1.inc
Labels: documentation, release

#1263 [release/public-v3.0.0] Final Updates to Release Branch
  README.md
  doc/UsersGuide/BackgroundInfo/CCPPUpdates.rst
  doc/UsersGuide/BackgroundInfo/Components.rst
  doc/UsersGuide/BackgroundInfo/Introduction.rst
  doc/UsersGuide/BackgroundInfo/TechnicalOverview.rst
  doc/UsersGuide/BuildingRunningTesting/BuildSRW.rst
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  doc/UsersGuide/BuildingRunningTesting/Quickstart.rst
Labels: documentation, release

#1264 [develop] Update build_gaeac5_intel.lua to allow SRW App to compile on Gaea C5
  doc/UsersGuide/BuildingRunningTesting/RunSRW.rst
  doc/UsersGuide/BuildingRunningTesting/VXCases.rst
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial4.inc
  doc/UsersGuide/BuildingRunningTesting/tutorials/tutorial6.inc
  modulefiles/build_gaeac5_intel.lua
Labels: bug, Priority: HIGH, run_we2e_coverage_tests

#1270 [develop] feat: misc smoke/dust updates following stakeholder feedback
  parm/FV3.input.yml
  tests/test_python/test_smoke_dust/conftest.py
  tests/test_python/test_smoke_dust/test_core/test_preprocessor.py
  tests/test_python/test_smoke_dust/test_core/test_regrid.py
  tests/test_python/test_smoke_dust/test_generate_emissions.py
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/smoke_dust/core/context.py
  ush/smoke_dust/core/regrid/common.py
  ush/smoke_dust/core/regrid/processor.py
  ush/smoke_dust/core/variable.py
Labels: enhancement, Priority: medium

#1200 [develop] Add NOAA Cloud coverage tests and skill-score WE2E to all coverage suites
  .cicd/Jenkinsfile
  .cicd/scripts/srw_metric.sh
  .cicd/scripts/srw_test.sh
  modulefiles/build_noaacloud_intel.lua
  parm/metplus/STATAnalysisConfig_skill_score
  tests/WE2E/machine_suites/coverage.derecho
  tests/WE2E/machine_suites/coverage.gaeac5
  tests/WE2E/machine_suites/coverage.gaeac6
  tests/WE2E/machine_suites/coverage.hera.gnu.com
  tests/WE2E/machine_suites/coverage.hera.intel.nco
  tests/WE2E/machine_suites/coverage.hercules
  tests/WE2E/machine_suites/coverage.noaacloud.aws
  tests/WE2E/machine_suites/coverage.noaacloud.azure
  tests/WE2E/machine_suites/coverage.noaacloud.gcp
  tests/WE2E/machine_suites/coverage.orion
  ush/machine/noaacloud.yaml
  ush/wrappers/job_cards/sbatch/get_ics.sbatch
  ush/wrappers/job_cards/sbatch/get_lbcs.sbatch
  ush/wrappers/job_cards/sbatch/make_grid.sbatch
  ush/wrappers/job_cards/sbatch/make_ics.sbatch
  ush/wrappers/job_cards/sbatch/make_lbcs.sbatch
  ush/wrappers/job_cards/sbatch/make_orog.sbatch
  ush/wrappers/job_cards/sbatch/make_sfc_climo.sbatch
  ush/wrappers/job_cards/sbatch/run_fcst.sbatch
  ush/wrappers/job_cards/sbatch/run_post.sbatch
Labels: run_we2e_coverage_tests

#1273 [develop] feat: history files can be written to FV3 native grid
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  parm/model_configure
  scripts/exregional_run_fcst.sh
  tests/test_python/test_create_model_configure_file.py
  ush/config.aqm.yaml
  ush/config_defaults.yaml
  ush/create_model_configure_file.py
Labels: enhancement

#1259 [develop] Add checks for correct SPP settings for the selected CCPP suite, resolve four more issues
  .github/CODEOWNERS
  .github/workflows/python_tests.yaml
  aqm_environment.yml
  doc/UsersGuide/BackgroundInfo/Components.rst
  doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
  environment.yml
  graphics_environment.yml
  parm/field_table.RRFS_sas
  sd_environment.yml
  tests/WE2E/machine_suites/comprehensive.derecho
  tests/WE2E/machine_suites/comprehensive.hera.gnu
  tests/WE2E/machine_suites/comprehensive.hera.intel
  tests/WE2E/machine_suites/comprehensive.noaacloud
  tests/WE2E/machine_suites/comprehensive.orion
  tests/WE2E/machine_suites/coverage.hera.intel.nco
  tests/WE2E/run_we2e_tests.py
  tests/WE2E/test_configs/smoke_dust/config.smoke_dust_grid_RRFS_CONUS_25km_suite_RRFS_sas.yaml
  tests/WE2E/test_configs/wflow_features/config.get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2mems.yaml
  ush/generate_FV3LAM_wflow.py
  ush/setup.py
Labels: run_we2e_coverage_tests

#1278 [develop] fix: adjust fire config for uwtools integration
  .gitignore
  doc/UsersGuide/BuildingRunningTesting/FIRE.rst
  ush/config.fire.yaml
  ush/machine/derecho.yaml
  ush/machine/gaeac5.yaml
  ush/machine/gaeac6.yaml
  ush/machine/hera.yaml
  ush/machine/hercules.yaml
  ush/machine/noaacloud.yaml
  ush/machine/orion.yaml
Labels: bug, Priority: medium
